config/routes.rb
ControlDeRebajos::Application.routes.draw do
  resources :conceptos

  resources :colaboradors

end

app/models/colaborador.rb
class Colaborador < ActiveRecord::Base
  belongs_to :concepto
end

app/models/concepto.rb
class Concepto < ActiveRecord::Base
  belongs_to :colaborador
  belongs_to :rebajo
end

app/models/rebajo.rb
class Rebajo < ActiveRecord::Base
  belongs_to :concepto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/colaboradors_controller.rb
class ColaboradorsController < ApplicationController
  # GET /colaboradors
  # GET /colaboradors.json
  def index
    @colaboradors = Colaborador.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colaboradors }
    end
  end

  # GET /colaboradors/1
  # GET /colaboradors/1.json
  def show
    @colaborador = Colaborador.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @colaborador }
    end
  end

  # GET /colaboradors/new
  # GET /colaboradors/new.json
  def new
    @colaborador = Colaborador.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @colaborador }
    end
  end

  # GET /colaboradors/1/edit
  def edit
    @colaborador = Colaborador.find(params[:id])
  end

  # POST /colaboradors
  # POST /colaboradors.json
  def create
    @colaborador = Colaborador.new(params[:colaborador])

    respond_to do |format|
      if @colaborador.save
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully created.' }
        format.json { render json: @colaborador, status: :created, location: @colaborador }
      else
        format.html { render action: "new" }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colaboradors/1
  # PUT /colaboradors/1.json
  def update
    @colaborador = Colaborador.find(params[:id])

    respond_to do |format|
      if @colaborador.update_attributes(params[:colaborador])
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaboradors/1
  # DELETE /colaboradors/1.json
  def destroy
    @colaborador = Colaborador.find(params[:id])
    @colaborador.destroy

    respond_to do |format|
      format.html { redirect_to colaboradors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/conceptos_controller.rb
class ConceptosController < ApplicationController
  # GET /conceptos
  # GET /conceptos.json
  def index
    @conceptos = Concepto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conceptos }
    end
  end

  # GET /conceptos/1
  # GET /conceptos/1.json
  def show
    @concepto = Concepto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concepto }
    end
  end

  # GET /conceptos/new
  # GET /conceptos/new.json
  def new
    @concepto = Concepto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concepto }
    end
  end

  # GET /conceptos/1/edit
  def edit
    @concepto = Concepto.find(params[:id])
  end

  # POST /conceptos
  # POST /conceptos.json
  def create
    @concepto = Concepto.new(params[:concepto])

    respond_to do |format|
      if @concepto.save
        format.html { redirect_to @concepto, notice: 'Concepto was successfully created.' }
        format.json { render json: @concepto, status: :created, location: @concepto }
      else
        format.html { render action: "new" }
        format.json { render json: @concepto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conceptos/1
  # PUT /conceptos/1.json
  def update
    @concepto = Concepto.find(params[:id])

    respond_to do |format|
      if @concepto.update_attributes(params[:concepto])
        format.html { redirect_to @concepto, notice: 'Concepto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @concepto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conceptos/1
  # DELETE /conceptos/1.json
  def destroy
    @concepto = Concepto.find(params[:id])
    @concepto.destroy

    respond_to do |format|
      format.html { redirect_to conceptos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colaboradors_helper.rb
module ColaboradorsHelper
end

app/helpers/conceptos_helper.rb
module ConceptosHelper
end

app/views/colaboradors/_form.html.erb
<%= form_for(@colaborador) do |f| %>
  <% if @colaborador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@colaborador.errors.count, "error") %> prohibited this colaborador from being saved:</h2>

      <ul>
      <% @colaborador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :salario_por_hora %><br />
    <%= f.text_field :salario_por_hora %>
  </div>
  <div class="field">
    <%= f.label :horas_por_quincena %><br />
    <%= f.number_field :horas_por_quincena %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :cedula %><br />
    <%= f.text_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :fecha_de_ingreso %><br />
    <%= f.date_select :fecha_de_ingreso %>
  </div>
  <div class="field">
    <%= f.label :fecha_de_nacimiento %><br />
    <%= f.date_select :fecha_de_nacimiento %>
  </div>
  <div class="field">
    <%= f.label :concepto %><br />
    <%= f.text_field :concepto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colaboradors/edit.html.erb
<h1>Editing colaborador</h1>

<%= render 'form' %>

<%= link_to 'Show', @colaborador %> |
<%= link_to 'Back', colaboradors_path %>

app/views/colaboradors/index.html.erb
<h1>Listing colaboradors</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Salario por hora</th>
    <th>Horas por quincena</th>
    <th>Codigo</th>
    <th>Cedula</th>
    <th>Fecha de ingreso</th>
    <th>Fecha de nacimiento</th>
    <th>Concepto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @colaboradors.each do |colaborador| %>
  <tr>
    <td><%= colaborador.nombre %></td>
    <td><%= colaborador.salario_por_hora %></td>
    <td><%= colaborador.horas_por_quincena %></td>
    <td><%= colaborador.codigo %></td>
    <td><%= colaborador.cedula %></td>
    <td><%= colaborador.fecha_de_ingreso %></td>
    <td><%= colaborador.fecha_de_nacimiento %></td>
    <td><%= colaborador.concepto %></td>
    <td><%= link_to 'Show', colaborador %></td>
    <td><%= link_to 'Edit', edit_colaborador_path(colaborador) %></td>
    <td><%= link_to 'Destroy', colaborador, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Colaborador', new_colaborador_path %>

app/views/colaboradors/new.html.erb
<h1>New colaborador</h1>

<%= render 'form' %>

<%= link_to 'Back', colaboradors_path %>

app/views/colaboradors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @colaborador.nombre %>
</p>

<p>
  <b>Salario por hora:</b>
  <%= @colaborador.salario_por_hora %>
</p>

<p>
  <b>Horas por quincena:</b>
  <%= @colaborador.horas_por_quincena %>
</p>

<p>
  <b>Codigo:</b>
  <%= @colaborador.codigo %>
</p>

<p>
  <b>Cedula:</b>
  <%= @colaborador.cedula %>
</p>

<p>
  <b>Fecha de ingreso:</b>
  <%= @colaborador.fecha_de_ingreso %>
</p>

<p>
  <b>Fecha de nacimiento:</b>
  <%= @colaborador.fecha_de_nacimiento %>
</p>

<p>
  <b>Concepto:</b>
  <%= @colaborador.concepto %>
</p>


<%= link_to 'Edit', edit_colaborador_path(@colaborador) %> |
<%= link_to 'Back', colaboradors_path %>

app/views/conceptos/_form.html.erb
<%= form_for(@concepto) do |f| %>
  <% if @concepto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concepto.errors.count, "error") %> prohibited this concepto from being saved:</h2>

      <ul>
      <% @concepto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :monto_total %><br />
    <%= f.text_field :monto_total %>
  </div>
  <div class="field">
    <%= f.label :frecuencia %><br />
    <%= f.number_field :frecuencia %>
  </div>
  <div class="field">
    <%= f.label :monto_actual %><br />
    <%= f.text_field :monto_actual %>
  </div>
  <div class="field">
    <%= f.label :colaborador %><br />
    <%= f.text_field :colaborador %>
  </div>
  <div class="field">
    <%= f.label :rebajo %><br />
    <%= f.text_field :rebajo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conceptos/edit.html.erb
<h1>Editing concepto</h1>

<%= render 'form' %>

<%= link_to 'Show', @concepto %> |
<%= link_to 'Back', conceptos_path %>

app/views/conceptos/index.html.erb
<h1>Listing conceptos</h1>

<table>
  <tr>
    <th>Monto total</th>
    <th>Frecuencia</th>
    <th>Monto actual</th>
    <th>Colaborador</th>
    <th>Rebajo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conceptos.each do |concepto| %>
  <tr>
    <td><%= concepto.monto_total %></td>
    <td><%= concepto.frecuencia %></td>
    <td><%= concepto.monto_actual %></td>
    <td><%= concepto.colaborador %></td>
    <td><%= concepto.rebajo %></td>
    <td><%= link_to 'Show', concepto %></td>
    <td><%= link_to 'Edit', edit_concepto_path(concepto) %></td>
    <td><%= link_to 'Destroy', concepto, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Concepto', new_concepto_path %>

app/views/conceptos/new.html.erb
<h1>New concepto</h1>

<%= render 'form' %>

<%= link_to 'Back', conceptos_path %>

app/views/conceptos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Monto total:</b>
  <%= @concepto.monto_total %>
</p>

<p>
  <b>Frecuencia:</b>
  <%= @concepto.frecuencia %>
</p>

<p>
  <b>Monto actual:</b>
  <%= @concepto.monto_actual %>
</p>

<p>
  <b>Colaborador:</b>
  <%= @concepto.colaborador %>
</p>

<p>
  <b>Rebajo:</b>
  <%= @concepto.rebajo %>
</p>


<%= link_to 'Edit', edit_concepto_path(@concepto) %> |
<%= link_to 'Back', conceptos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ControlDeRebajos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>